/* V15 core: Google auth, membership and safe V14 migration. */
(function(){
'use strict';
const V={
 VERSION:15,INSTITUTE_ID:'brdbagiti-mumbai-01',INSTITUTE_NAME:'Bharat Ratna Dr. Babasaheb Ambedkar Government ITI, Mumbai-01',
 fb:{M:null,app:null,auth:null,db:null,user:null},member:null,workspaceId:null,ready:false,syncing:false,suppressLocalSync:false,shadow:null,unsubscribers:[],arraySections:new Set(),mapSections:new Set(),pendingTimer:null,
 esc(v){return String(v??'').trim().toLowerCase().replace(/[^a-z0-9._@-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,180)||'record';},
 clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}},eq(a,b){try{return JSON.stringify(a)===JSON.stringify(b);}catch(e){return false;}},now(){return new Date().toISOString();},
 email(v){return String(v||'').trim().toLowerCase();},validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(this.email(v));},code(){return String(Math.floor(100000+Math.random()*900000));},
 async hash(v){const b=new TextEncoder().encode(String(v)),d=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('');},
 safe(v){const x=this.clone(v);if(x&&typeof x==='object'){delete x.pin;if(x.dataUrl&&String(x.dataUrl).startsWith('data:'))delete x.dataUrl;}return x;},
 wid(meta){const m=meta||DATA?.meta||{};return this.esc(`${m.instituteCode||m.institute||'iti'}-${m.trade||'trade'}-${m.session||'session'}`).slice(0,120);},
 itemId(s,x,i=0){if(x?.id!=null)return this.esc(x.id);if(x?.no!=null)return'n-'+this.esc(x.no);if(x?.roll)return'roll-'+this.esc(x.roll);if(x?.code)return'code-'+this.esc(x.code);if(x?.date&&x?.label)return'date-'+this.esc(x.date+'-'+x.label);return'i-'+String(i).padStart(5,'0');},
 async modules(){if(this.fb.M)return this.fb.M;if(window.CloudCenter?.firebaseModules)this.fb.M=await CloudCenter.firebaseModules();else{const v='12.16.0',[a,b,c]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${v}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${v}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${v}/firebase-firestore.js`)]);this.fb.M={...a,...b,...c};}return this.fb.M;},
 config(){try{const s=JSON.parse(localStorage.getItem('iti-v14-cloud-settings')||'{}'),c=typeof s.firebaseConfig==='string'?JSON.parse(s.firebaseConfig):s.firebaseConfig;if(c?.apiKey&&c?.projectId&&c?.appId)return c;}catch(e){}return{apiKey:'AIzaSyBqfRWJT9h9JKBWNUYpkSG2olHinOSZdEM',authDomain:'universal-iti-auto-dk.firebaseapp.com',projectId:'universal-iti-auto-dk',storageBucket:'universal-iti-auto-dk.firebasestorage.app',messagingSenderId:'337752379271',appId:'1:337752379271:web:5c30c0855a118cf604cd22',measurementId:'G-JEXW0X54KF'};},
 async google(promptUser=true){const M=await this.modules(),cfg=this.config();let app=M.getApps().find(x=>x.name==='iti-v15');if(!app)app=M.initializeApp(cfg,'iti-v15');const auth=M.getAuth(app);await M.setPersistence(auth,M.browserLocalPersistence);let user=auth.currentUser;if(!user||promptUser){const p=new M.GoogleAuthProvider();p.setCustomParameters({prompt:'select_account'});user=(await M.signInWithPopup(auth,p)).user;}this.fb={M,app,auth,db:M.getFirestore(app),user};return user;},
 inst(){return this.fb.M.doc(this.fb.db,'institutes',this.INSTITUTE_ID);},memberRef(uid=this.fb.user?.uid){return this.fb.M.doc(this.fb.db,'institutes',this.INSTITUTE_ID,'members',uid);},access(email){return this.fb.M.doc(this.fb.db,'institutes',this.INSTITUTE_ID,'access',this.email(email));},secret(email){return this.fb.M.doc(this.fb.db,'institutes',this.INSTITUTE_ID,'inviteSecrets',this.email(email));},
 ws(w=this.workspaceId){return this.fb.M.doc(this.fb.db,'institutes',this.INSTITUTE_ID,'workspaces',w);},col(s,w=this.workspaceId){return this.fb.M.collection(this.fb.db,'institutes',this.INSTITUTE_ID,'workspaces',w,s);},state(k,w=this.workspaceId){return this.fb.M.doc(this.fb.db,'institutes',this.INSTITUTE_ID,'workspaces',w,'state',this.esc(k));},
 async legacy(){const M=this.fb.M,uid=this.fb.user.uid;let w='';try{w=window.CloudCenter?.workspaceId?.()||'';}catch(e){}if(!w)w=this.wid(DATA?.meta||{});try{const s=await M.getDocs(M.collection(this.fb.db,'itiInstructorUsers',uid,'workspaces',w,'sections'));if(s.empty)return null;const d={};s.forEach(r=>{const x=r.data();if(x.key&&!String(x.key).startsWith('_')&&x.key!=='galleryIndex')d[x.key]=x.value;});return d.meta?d:null;}catch(e){return null;}},
 localRecords(){return !!DATA&&((DATA.trainees||[]).length||Object.keys(DATA.attendance||{}).length||Object.keys(DATA.marks||{}).length||(DATA.notices||[]).length);},
 async readMember(){const s=await this.fb.M.getDoc(this.memberRef());this.member=s.exists()?s.data():null;return this.member;},
 async bootstrap(role,legacy){const M=this.fb.M,u=this.fb.user;if((await M.getDoc(this.inst())).exists())return false;const meta=legacy?.meta||DATA?.meta||{},w=this.wid(meta);await M.setDoc(this.inst(),{name:meta.institute||this.INSTITUTE_NAME,code:meta.instituteCode||'MUMBAI-01',schemaVersion:15,ownerUid:u.uid,createdAt:this.now(),updatedAt:this.now()});await M.setDoc(this.memberRef(),{uid:u.uid,email:this.email(u.email),displayName:u.displayName||meta.instructor||'Owner',role:role==='student'?'instructor':role,active:true,owner:true,workspaceIds:[w],createdAt:this.now()});this.member=(await M.getDoc(this.memberRef())).data();this.workspaceId=w;return true;},
 async activate(role){const M=this.fb.M,email=this.email(this.fb.user.email);let a;try{const s=await M.getDoc(this.access(email));if(!s.exists())return'not-authorized';a=s.data();}catch(e){return'not-authorized';}if(a.active===false)return'disabled';if(a.role!==role)return'approved-as-'+a.role;const c=String(prompt(`First login activation for ${email}\nEnter the 6-digit code given by your ${a.role==='student'?'instructor':'administrator'}:`)||'').trim();if(!/^\d{6}$/.test(c))return'invalid-code';const proof=await this.hash(c),m={uid:this.fb.user.uid,email,displayName:a.displayName||this.fb.user.displayName||email,role:a.role,active:true,owner:false,workspaceIds:a.workspaceIds||[],traineeId:a.traineeId||null,activationProof:proof,createdAt:this.now()};try{await M.setDoc(this.memberRef(),m);this.member=m;return'ok';}catch(e){return'wrong-code-or-rules';}},
 roleOK(role){return !!this.member&&this.member.active!==false&&((this.member.owner&&['principal','instructor'].includes(role))||this.member.role===role);},
 sections(src){const a=[],m=[],z=[];Object.keys(src||{}).forEach(k=>{if(k==='users'||k==='meta')return;const v=src[k];if(Array.isArray(v))a.push(k);else if(v&&typeof v==='object')m.push(k);else z.push(k);});return{a,m,z};},
 async writeMapFull(s,obj,w=this.workspaceId){const M=this.fb.M;if(['attendance','marks','submissions'].includes(s)){for(const[k,v]of Object.entries(obj||{}))for(const[sk,val]of Object.entries(v||{}))await M.setDoc(M.doc(this.col(s,w),this.esc(k+'--'+sk)),{key:k,subKey:sk,traineeId:sk,data:this.safe(val),updatedAt:this.now(),updatedBy:this.fb.user.uid});}else for(const[k,val]of Object.entries(obj||{}))await M.setDoc(M.doc(this.col('map_'+s,w),this.esc(k)),{key:k,data:this.safe(val),updatedAt:this.now(),updatedBy:this.fb.user.uid});},
 async migrate(src,from='V14'){const M=this.fb.M,meta=this.safe(src.meta||{});this.workspaceId=this.workspaceId||this.wid(meta);delete meta.instructorPin;delete meta.principalPin;const{a,m,z}=this.sections(src);this.arraySections=new Set(a.filter(x=>x!=='gallery'));this.mapSections=new Set(m);await M.setDoc(this.ws(),{...meta,schemaVersion:15,appVersion:'V15',workspaceId:this.workspaceId,instituteId:this.INSTITUTE_ID,migratedFrom:from,migratedAt:this.now(),arraySections:[...this.arraySections],mapSections:[...this.mapSections]},{merge:true});for(const s of a){if(s==='gallery')continue;for(let i=0;i<(src[s]||[]).length;i++){const x=src[s][i];await M.setDoc(M.doc(this.col(s),this.itemId(s,x,i)),{data:this.safe(x),updatedAt:this.now(),updatedBy:this.fb.user.uid});}}for(const s of m)await this.writeMapFull(s,src[s]||{});for(const s of z)await M.setDoc(this.state(s),{value:this.clone(src[s]),updatedAt:this.now(),updatedBy:this.fb.user.uid});},
 async login(role){this.loginMsg('Connecting securely with Google…');try{await this.google(true);let legacy=null,m=await this.readMember();if(!m){legacy=await this.legacy();let exists=false;try{exists=(await this.fb.M.getDoc(this.inst())).exists();}catch(e){if(String(e.code||'').includes('permission-denied'))throw new Error('V15 Firestore rules are not published yet. Your V14 records are unchanged.');}if(!exists&&role!=='student'&&(legacy||this.localRecords())){await this.bootstrap(role,legacy);m=this.member;}else{const r=await this.activate(role);if(r!=='ok'){await this.fb.M.signOut(this.fb.auth).catch(()=>{});this.loginMsg(r==='not-authorized'?'This Google account is not approved for this institute.':r.startsWith('approved-as-')?`This account is approved as ${r.slice(12)}, not ${role}.`:r==='invalid-code'?'Activation cancelled or code format is invalid.':'Activation failed. Check the code and V15 Firestore rules.',true);return;}m=this.member;}}if(!this.roleOK(role)){this.loginMsg(`Access denied. This Google account is registered as ${m?.role||'another role'}.`,true);return;}this.workspaceId=this.workspaceId||(m.workspaceIds||[])[0]||this.wid(legacy?.meta||DATA?.meta||{});let shared=false;try{shared=(await this.fb.M.getDoc(this.ws())).exists();}catch(e){throw new Error('V15 Firestore rules are not published yet. Your V14 records are unchanged.');}if(!shared){if(!legacy)legacy=await this.legacy();if(legacy){this.loginMsg('Preserving your V14 records and migrating them to V15 shared cloud…');await this.migrate(legacy,'V14');}else if(m.owner&&DATA)await this.migrate(DATA,'local');else throw new Error('No shared workspace exists yet. Ask the owner/instructor to finish migration.');}await this.load(role);SESSION={role,name:m.displayName||this.fb.user.displayName||this.fb.user.email,userId:this.fb.user.uid,username:this.email(this.fb.user.email),traineeId:m.traineeId||null,googleEmail:this.email(this.fb.user.email)};this.ready=true;this.shadow=this.clone(DATA);this.disableLegacy();this.realtime(role);App.enter();const b=document.getElementById('changePinBtn');if(b)b.style.display='none';this.refresh();this.cloudUI();this.loginMsg('');}catch(e){console.error(e);this.loginMsg(e.code==='auth/popup-closed-by-user'?'Google sign-in was cancelled.':(e.message||String(e)),true);}},
 async logout(){this.unsubscribers.forEach(f=>{try{f();}catch(e){}});try{if(this.fb.auth)await this.fb.M.signOut(this.fb.auth);}catch(e){}SESSION=null;this.ready=false;try{localStorage.removeItem(SESSION_KEY);}catch(e){}location.reload();}
};
window.V15Sync=V;
})();
