/* V15 UI/bootstrap. */
(function(V){
'use strict';
Object.assign(V,{
 loginMsg(t,err=false){const e=document.getElementById('v15LoginStatus');if(!e)return;e.style.display=t?'block':'none';e.textContent=t;e.className='callout '+(err?'cloud-error':'');},
 disableLegacy(){try{if(window.CloudCenter){CloudCenter.cfg.autoSync=false;CloudCenter.scheduleSync=()=>{};}}catch(e){}},
 cloudUI(){const c=document.getElementById('cloudFirebaseConfig');if(c?.closest('.field'))c.closest('.field').style.display='none';const a=document.getElementById('cloudAutoSync');if(a?.closest('label'))a.closest('label').style.display='none';document.querySelectorAll('[onclick*="CloudCenter.pushNow"],[onclick*="CloudCenter.restoreFromCloud"],[onclick*="CloudCenter.connectFirebase"],[onclick*="CloudCenter.disconnectFirebase"],[onclick*="CloudCenter.saveSettings"]').forEach(b=>b.style.display='none');const card=c?.closest('.card');if(card&&!document.getElementById('v15RealtimePanel')){const d=document.createElement('div');d.id='v15RealtimePanel';d.innerHTML=`<div class="callout cloud-ok"><b>V15 Shared Realtime Cloud</b><br><span id="v15RealtimeBadge">● Synced</span> — ${this.fb.user?.email||''}<br><small>Firebase is built in. No Push/Restore is needed on another device.</small></div><div class="field-row" style="margin-top:12px"><div class="field" style="flex:2"><label>Approve staff Google email</label><input id="v15InviteEmail" type="email" placeholder="instructor@gmail.com"></div><div class="field" style="flex:1"><label>Role</label><select id="v15InviteRole"><option value="instructor">Instructor</option><option value="principal">Principal</option></select></div></div><button class="btn secondary" id="v15InviteBtn">Create first-login code</button><p class="muted small-note">Students are approved in Trainee Master using Set Gmail. Different devices write record-by-record to Firestore instead of replacing the whole trainee list.</p>`;card.insertBefore(d,card.firstChild.nextSibling);d.querySelector('#v15InviteBtn').onclick=()=>V.inviteStaffUI();}},
 wrapSave(){if(typeof saveData!=='function'||saveData.__v15)return;const o=saveData;saveData=function(){const r=o();if(!V.suppressLocalSync)V.schedule();return r;};saveData.__v15=true;},
 loginUI(){document.title='Universal ITI Instructor Automation V15';const n=document.querySelector('.login-note');if(n)n.textContent='Universal Instructor Automation V15 — Secure Google login + shared realtime Firebase records.';const k=document.querySelector('.showcase-kicker');if(k)k.textContent='REALTIME MULTI-USER WORKSPACE';const f=document.querySelector('.showcase-footer');if(f)f.textContent='Government ITI workflow • Shared Firebase records • Multi-device';const hide=()=>['staffNameField','staffPinField','studentRollField','studentPinField'].forEach(id=>{const e=document.getElementById(id);if(e)e.style.display='none';});hide();const b=document.querySelector('#loginScreen button[onclick="App.login()"]');if(b){b.textContent='🔐 Continue with Google';b.removeAttribute('onclick');b.onclick=()=>V.login(document.getElementById('loginRole')?.value||'instructor');}if(!document.getElementById('v15LoginStatus')){const p=document.createElement('div');p.id='v15LoginStatus';p.className='callout';p.style.display='none';p.style.marginTop='12px';b?.insertAdjacentElement('afterend',p);}const r=document.getElementById('loginRole');if(r)r.onchange=hide;App.login=()=>V.login(document.getElementById('loginRole')?.value||'instructor');App.logout=()=>V.logout();},
 install(){this.loginUI();this.traineeUI();this.wrapSave();this.disableLegacy();console.info('Universal ITI V15 realtime layer ready. V14 local/cloud records are preserved until migration succeeds.');}
});
V.install();
})(window.V15Sync);
