plugins {
    id 'com.android.application'
}

android {
    namespace 'in.universaliti.automation'
    compileSdk 35

    defaultConfig {
        applicationId 'in.universaliti.automation'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0-rc1'
    }
}

dependencies {
    implementation 'androidx.browser:browser:1.8.0'
}
